### ISSUE TITLE
Hybrid comm protocol v1.1.23

### ISSUE THREAD

**Issue by bjeanes** [bohdan-s/Sungrow-Inverter#1]
[TI_20211231_Communication Protocol of Residential Hybrid Inverter_V1.0.23_EN.pdf](https://github.com/bohdan-s/Sungrow-Inverter/files/9075558/TI_20211231_Communication.Protocol.of.Residential.Hybrid.Inverter_V1.0.23_EN.pdf)

**Comment by bjeanes** [comment]
[TI_20211225_Communication Protocol of PV Grid-Connected String Inverters_V1.1.40_EN.pdf](https://github.com/bohdan-s/Sungrow-Inverter/files/10150344/TI_20211225_Communication.Protocol.of.PV.Grid-Connected.String.Inverters_V1.1.40_EN.pdf)

I just received v1.1.40

**Comment by Gnarfoz** [comment]
This is version 1.0.23, not 1.1.23. Could still be added to keep track of historical changes.

**Comment by Gnarfoz** [comment]
I've created a pull request for this (and other versions): #3
